name: nyxx_commands
version: 5.0.2
description: A framework for easily creating slash commands and text commands for Discord using the nyxx library.

homepage: https://github.com/nyxx-discord/nyxx_commands/blob/main/README.md
repository: https://github.com/nyxx-discord/nyxx_commands
issue_tracker: https://github.com/nyxx-discord/nyxx_commands/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.7.1
  args: ^2.4.0
  dart_style: ^2.2.5
  logging: ^1.1.1
  meta: ^1.9.0
  nyxx: ^5.0.0
  nyxx_interactions: ^4.6.0
  random_string: ^2.3.1
  path: ^1.8.3
  runtime_type: ^1.0.1
  fuzzywuzzy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.0
  coverage: ^1.6.3
  lints: ^2.0.1
  mockito: ^5.3.2
  test: ^1.23.1

executables:
  nyxx-compile: compile
