name: nyxx_commands
version: 6.1.0
description: A framework for easily creating slash commands and text commands for Discord using the nyxx library.

homepage: https://github.com/nyxx-discord/nyxx_commands/blob/main/README.md
repository: https://github.com/nyxx-discord/nyxx_commands
issue_tracker: https://github.com/nyxx-discord/nyxx_commands/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  args: ^2.7.0
  dart_style: ^2.3.2
  logging: ^1.3.0
  nyxx: ^6.8.0
  path: ^1.9.1
  runtime_type: ^1.1.0
  fuzzywuzzy: ^1.2.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.13
  coverage: ^1.15.0
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.8

executables:
  nyxx-compile: compile
